name: XY-ULTIMATE-EXTRACTOR

on:
  repository_dispatch:
    types: [trigger_scrape]
  workflow_dispatch:

jobs:
  penetration:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: xyjem
        uses: actions/checkout@v4
      
      - name: action
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: instal
        run: |
          npm install
          npx playwright install chromium --with-deps
        
      - name: nodek
        run: node scraper.js
        env:
          XY_GIST_TOKEN: ${{ secrets.XY_GIST_TOKEN }}
          
      - name: push
        run: |
          git config --global user.name "Trojan-Bot"
          git config --global user.email "haekalsaputra01h@gmail.com"
          git add .
          git commit -m "Auto-Harvest: [$(date)]" || echo "No changes"
          git push
