name: XY Trojan Node Scraper

on:
  repository_dispatch:
    types: [trigger_scrape]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Hapus baris cache: 'npm' sementara agar tidak error lock file
          
      - name: Install Dependencies
        # Pakai npm install biasa dulu
        run: npm install
        
      - name: Run Scraper
        run: node scraper.js
        env:
          XY_GIST_TOKEN: ${{ secrets.XY_GIST_TOKEN }}
          
      - name: Push Result
        run: |
          git config --global user.name "Trojan-Bot"
          git config --global user.email "haekalsaputra01h@gmail.com"
          git add .
          git commit -m "Auto Harvest [$(date)]" || echo "No changes"
          git push
